In [115]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import preprocessing
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import pickle
from ast import literal_eval
%matplotlib inline

In [116]:
data = pd.read_csv("C:/CHARACTOR_RECOGNITION/NEW_DATA_FINAL.csv")
data

Ratio0  Ratio1  Ratio2  Ratio3  Ratio4  Ratio5  Ratio6  Ratio7  \
0       5.70   14.91    7.89   21.49    4.39   17.54    6.58   21.49   
1       5.06   15.73    8.43   19.10    5.06   19.10    5.06   22.47   
2       7.14    9.82    7.14   26.34    4.46   14.29    5.36   25.45   
3       6.79   10.86    5.88   27.60    4.52   13.12    5.88   25.34   
4       9.24   11.96    6.52   23.37    6.52   15.22    5.98   21.20   
...      ...     ...     ...     ...     ...     ...     ...     ...   
5054    4.88    7.32   14.63   24.39    2.44    9.76   14.63   21.95   
5055   10.26   10.26    7.69   25.64   10.26    2.56   15.38   17.95   
5056    9.52   14.29    9.52   17.46    9.52   12.70   11.11   15.87   
5057    9.68    3.23   16.13   25.81    6.45    0.00   22.58   16.13   
5058   14.29    5.71   17.14   14.29   11.43    8.57   17.14   11.43   

                                                     LR  \
0     [50, 50, 14, 10, 9, 7, 6, 5, 5, 5, 5, 5, 21, 1...   
1     [50, 50, 50, 50, 14, 11, 8, 7, 6, 6, 6, 6, 6, ...   
2     [50, 50, 50, 50, 50, 19, 13, 10, 8, 7, 7, 7, 7...   
3     [50, 50, 50, 12, 10, 8, 6, 5, 5, 4, 4, 4, 4, 4...   
4     [50, 50, 50, 50, 15, 11, 9, 8, 7, 7, 7, 8, 7, ...   
...                                                 ...   
5054  [50, 50, 50, 50, 50, 50, 50, 50, 31, 28, 26, 2...   
5055  [50, 50, 50, 50, 50, 50, 50, 50, 50, 26, 24, 2...   
5056  [50, 50, 30, 27, 25, 23, 22, 21, 20, 19, 18, 1...   
5057  [50, 50, 50, 50, 50, 50, 50, 50, 50, 27, 25, 2...   
5058  [50, 50, 50, 50, 50, 50, 50, 50, 30, 28, 27, 2...   

                                                     RL  \
0     [49, 49, 19, 18, 17, 17, 16, 7, 6, 6, 6, 6, 6,...   
1     [49, 49, 49, 49, 24, 22, 21, 7, 7, 6, 6, 6, 6,...   
2     [49, 49, 49, 49, 49, 18, 16, 14, 12, 11, 11, 1...   
3     [49, 49, 49, 18, 16, 15, 6, 5, 5, 4, 4, 4, 4, ...   
4     [49, 49, 49, 49, 27, 25, 23, 9, 8, 8, 7, 7, 7,...   
...                                                 ...   
5054  [49, 49, 49, 49, 49, 49, 49, 49, 15, 13, 12, 1...   
5055  [49, 49, 49, 49, 49, 49, 49, 49, 49, 16, 13, 1...   
5056  [49, 49, 16, 13, 12, 11, 10, 9, 9, 8, 8, 8, 7,...   
5057  [49, 49, 49, 49, 49, 49, 49, 49, 49, 15, 14, 1...   
5058  [49, 49, 49, 49, 49, 49, 49, 49, 15, 14, 13, 1...   

                                                     TB  \
0     [50, 50, 50, 50, 22, 7, 6, 5, 5, 4, 3, 3, 3, 3...   
1     [50, 50, 50, 25, 22, 20, 8, 7, 6, 6, 6, 5, 5, ...   
2     [50, 50, 50, 50, 50, 24, 23, 9, 8, 8, 7, 7, 7,...   
3     [50, 50, 25, 23, 9, 7, 6, 6, 5, 5, 4, 4, 3, 3,...   
4     [50, 50, 50, 50, 23, 21, 20, 8, 7, 6, 6, 5, 5,...   
...                                                 ...   
5054  [50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 2...   
5055  [50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 23, 2...   
5056  [50, 50, 50, 50, 50, 50, 50, 50, 26, 24, 22, 2...   
5057  [50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 33, 3...   
5058  [50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 5...   

                                                     BT  \
0     [49, 49, 49, 49, 16, 14, 13, 13, 12, 12, 11, 1...   
1     [49, 49, 49, 15, 13, 12, 11, 11, 11, 10, 10, 1...   
2     [49, 49, 49, 49, 49, 19, 17, 16, 15, 15, 14, 1...   
3     [49, 49, 21, 18, 17, 16, 14, 13, 13, 13, 12, 1...   
4     [49, 49, 49, 49, 20, 17, 15, 14, 13, 13, 12, 1...   
...                                                 ...   
5054  [49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 2...   
5055  [49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 10, 9...   
5056  [49, 49, 49, 49, 49, 49, 49, 49, 4, 3, 3, 2, 2...   
5057  [49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 10, 1...   
5058  [49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 4...   

                                                Density Group     label   Num  \
0     [0.2764, 0.2536, 0.1944, 0.236, 0.1122, 0.2279...     D      0D85   1.0   
1     [0.2644, 0.2243, 0.2762, 0.2724, 0.1038, 0.092...     D      0D85   1.0   
2     [0.2157, 0.1421, 0.2242, 0.3177, 0.1107, 0.111...     D 

In [117]:
ex =data.drop('Group', axis=1)
ex =ex.drop('label', axis=1)
ex =ex.drop('unicode', axis=1)
X =ex.drop('Num', axis=1)
y = data['unicode']
X

Ratio0  Ratio1  Ratio2  Ratio3  Ratio4  Ratio5  Ratio6  Ratio7  \
0       5.70   14.91    7.89   21.49    4.39   17.54    6.58   21.49   
1       5.06   15.73    8.43   19.10    5.06   19.10    5.06   22.47   
2       7.14    9.82    7.14   26.34    4.46   14.29    5.36   25.45   
3       6.79   10.86    5.88   27.60    4.52   13.12    5.88   25.34   
4       9.24   11.96    6.52   23.37    6.52   15.22    5.98   21.20   
...      ...     ...     ...     ...     ...     ...     ...     ...   
5054    4.88    7.32   14.63   24.39    2.44    9.76   14.63   21.95   
5055   10.26   10.26    7.69   25.64   10.26    2.56   15.38   17.95   
5056    9.52   14.29    9.52   17.46    9.52   12.70   11.11   15.87   
5057    9.68    3.23   16.13   25.81    6.45    0.00   22.58   16.13   
5058   14.29    5.71   17.14   14.29   11.43    8.57   17.14   11.43   

                                                     LR  \
0     [50, 50, 14, 10, 9, 7, 6, 5, 5, 5, 5, 5, 21, 1...   
1     [50, 50, 50, 50, 14, 11, 8, 7, 6, 6, 6, 6, 6, ...   
2     [50, 50, 50, 50, 50, 19, 13, 10, 8, 7, 7, 7, 7...   
3     [50, 50, 50, 12, 10, 8, 6, 5, 5, 4, 4, 4, 4, 4...   
4     [50, 50, 50, 50, 15, 11, 9, 8, 7, 7, 7, 8, 7, ...   
...                                                 ...   
5054  [50, 50, 50, 50, 50, 50, 50, 50, 31, 28, 26, 2...   
5055  [50, 50, 50, 50, 50, 50, 50, 50, 50, 26, 24, 2...   
5056  [50, 50, 30, 27, 25, 23, 22, 21, 20, 19, 18, 1...   
5057  [50, 50, 50, 50, 50, 50, 50, 50, 50, 27, 25, 2...   
5058  [50, 50, 50, 50, 50, 50, 50, 50, 30, 28, 27, 2...   

                                                     RL  \
0     [49, 49, 19, 18, 17, 17, 16, 7, 6, 6, 6, 6, 6,...   
1     [49, 49, 49, 49, 24, 22, 21, 7, 7, 6, 6, 6, 6,...   
2     [49, 49, 49, 49, 49, 18, 16, 14, 12, 11, 11, 1...   
3     [49, 49, 49, 18, 16, 15, 6, 5, 5, 4, 4, 4, 4, ...   
4     [49, 49, 49, 49, 27, 25, 23, 9, 8, 8, 7, 7, 7,...   
...                                                 ...   
5054  [49, 49, 49, 49, 49, 49, 49, 49, 15, 13, 12, 1...   
5055  [49, 49, 49, 49, 49, 49, 49, 49, 49, 16, 13, 1...   
5056  [49, 49, 16, 13, 12, 11, 10, 9, 9, 8, 8, 8, 7,...   
5057  [49, 49, 49, 49, 49, 49, 49, 49, 49, 15, 14, 1...   
5058  [49, 49, 49, 49, 49, 49, 49, 49, 15, 14, 13, 1...   

                                                     TB  \
0     [50, 50, 50, 50, 22, 7, 6, 5, 5, 4, 3, 3, 3, 3...   
1     [50, 50, 50, 25, 22, 20, 8, 7, 6, 6, 6, 5, 5, ...   
2     [50, 50, 50, 50, 50, 24, 23, 9, 8, 8, 7, 7, 7,...   
3     [50, 50, 25, 23, 9, 7, 6, 6, 5, 5, 4, 4, 3, 3,...   
4     [50, 50, 50, 50, 23, 21, 20, 8, 7, 6, 6, 5, 5,...   
...                                                 ...   
5054  [50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 2...   
5055  [50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 23, 2...   
5056  [50, 50, 50, 50, 50, 50, 50, 50, 26, 24, 22, 2...   
5057  [50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 33, 3...   
5058  [50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 5...   

                                                     BT  \
0     [49, 49, 49, 49, 16, 14, 13, 13, 12, 12, 11, 1...   
1     [49, 49, 49, 15, 13, 12, 11, 11, 11, 10, 10, 1...   
2     [49, 49, 49, 49, 49, 19, 17, 16, 15, 15, 14, 1...   
3     [49, 49, 21, 18, 17, 16, 14, 13, 13, 13, 12, 1...   
4     [49, 49, 49, 49, 20, 17, 15, 14, 13, 13, 12, 1...   
...                                                 ...   
5054  [49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 2...   
5055  [49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 10, 9...   
5056  [49, 49, 49, 49, 49, 49, 49, 49, 4, 3, 3, 2, 2...   
5057  [49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 10, 1...   
5058  [49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 4...   

                                                Density  
0     [0.2764, 0.2536, 0.1944, 0.236, 0.1122, 0.2279...  
1     [0.2644, 0.2243, 0.2762, 0.2724, 0.1038, 0.092...  
2     [0.2157, 0.1421, 0.2242, 0.3177, 0.1107, 0.111...  
3     [0.2602, 0.2562, 0.2928, 0.2821, 0.136, 0.1082...  
4     [0.2199, 

In [118]:
X.dropna()

Ratio0  Ratio1  Ratio2  Ratio3  Ratio4  Ratio5  Ratio6  Ratio7  \
0       5.70   14.91    7.89   21.49    4.39   17.54    6.58   21.49   
1       5.06   15.73    8.43   19.10    5.06   19.10    5.06   22.47   
2       7.14    9.82    7.14   26.34    4.46   14.29    5.36   25.45   
3       6.79   10.86    5.88   27.60    4.52   13.12    5.88   25.34   
4       9.24   11.96    6.52   23.37    6.52   15.22    5.98   21.20   
...      ...     ...     ...     ...     ...     ...     ...     ...   
5054    4.88    7.32   14.63   24.39    2.44    9.76   14.63   21.95   
5055   10.26   10.26    7.69   25.64   10.26    2.56   15.38   17.95   
5056    9.52   14.29    9.52   17.46    9.52   12.70   11.11   15.87   
5057    9.68    3.23   16.13   25.81    6.45    0.00   22.58   16.13   
5058   14.29    5.71   17.14   14.29   11.43    8.57   17.14   11.43   

                                                     LR  \
0     [50, 50, 14, 10, 9, 7, 6, 5, 5, 5, 5, 5, 21, 1...   
1     [50, 50, 50, 50, 14, 11, 8, 7, 6, 6, 6, 6, 6, ...   
2     [50, 50, 50, 50, 50, 19, 13, 10, 8, 7, 7, 7, 7...   
3     [50, 50, 50, 12, 10, 8, 6, 5, 5, 4, 4, 4, 4, 4...   
4     [50, 50, 50, 50, 15, 11, 9, 8, 7, 7, 7, 8, 7, ...   
...                                                 ...   
5054  [50, 50, 50, 50, 50, 50, 50, 50, 31, 28, 26, 2...   
5055  [50, 50, 50, 50, 50, 50, 50, 50, 50, 26, 24, 2...   
5056  [50, 50, 30, 27, 25, 23, 22, 21, 20, 19, 18, 1...   
5057  [50, 50, 50, 50, 50, 50, 50, 50, 50, 27, 25, 2...   
5058  [50, 50, 50, 50, 50, 50, 50, 50, 30, 28, 27, 2...   

                                                     RL  \
0     [49, 49, 19, 18, 17, 17, 16, 7, 6, 6, 6, 6, 6,...   
1     [49, 49, 49, 49, 24, 22, 21, 7, 7, 6, 6, 6, 6,...   
2     [49, 49, 49, 49, 49, 18, 16, 14, 12, 11, 11, 1...   
3     [49, 49, 49, 18, 16, 15, 6, 5, 5, 4, 4, 4, 4, ...   
4     [49, 49, 49, 49, 27, 25, 23, 9, 8, 8, 7, 7, 7,...   
...                                                 ...   
5054  [49, 49, 49, 49, 49, 49, 49, 49, 15, 13, 12, 1...   
5055  [49, 49, 49, 49, 49, 49, 49, 49, 49, 16, 13, 1...   
5056  [49, 49, 16, 13, 12, 11, 10, 9, 9, 8, 8, 8, 7,...   
5057  [49, 49, 49, 49, 49, 49, 49, 49, 49, 15, 14, 1...   
5058  [49, 49, 49, 49, 49, 49, 49, 49, 15, 14, 13, 1...   

                                                     TB  \
0     [50, 50, 50, 50, 22, 7, 6, 5, 5, 4, 3, 3, 3, 3...   
1     [50, 50, 50, 25, 22, 20, 8, 7, 6, 6, 6, 5, 5, ...   
2     [50, 50, 50, 50, 50, 24, 23, 9, 8, 8, 7, 7, 7,...   
3     [50, 50, 25, 23, 9, 7, 6, 6, 5, 5, 4, 4, 3, 3,...   
4     [50, 50, 50, 50, 23, 21, 20, 8, 7, 6, 6, 5, 5,...   
...                                                 ...   
5054  [50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 2...   
5055  [50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 23, 2...   
5056  [50, 50, 50, 50, 50, 50, 50, 50, 26, 24, 22, 2...   
5057  [50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 33, 3...   
5058  [50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 5...   

                                                     BT  \
0     [49, 49, 49, 49, 16, 14, 13, 13, 12, 12, 11, 1...   
1     [49, 49, 49, 15, 13, 12, 11, 11, 11, 10, 10, 1...   
2     [49, 49, 49, 49, 49, 19, 17, 16, 15, 15, 14, 1...   
3     [49, 49, 21, 18, 17, 16, 14, 13, 13, 13, 12, 1...   
4     [49, 49, 49, 49, 20, 17, 15, 14, 13, 13, 12, 1...   
...                                                 ...   
5054  [49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 2...   
5055  [49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 10, 9...   
5056  [49, 49, 49, 49, 49, 49, 49, 49, 4, 3, 3, 2, 2...   
5057  [49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 10, 1...   
5058  [49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 4...   

                                                Density  
0     [0.2764, 0.2536, 0.1944, 0.236, 0.1122, 0.2279...  
1     [0.2644, 0.2243, 0.2762, 0.2724, 0.1038, 0.092...  
2     [0.2157, 0.1421, 0.2242, 0.3177, 0.1107, 0.111...  
3     [0.2602, 0.2562, 0.2928, 0.2821, 0.136, 0.1082...  
4     [0.2199, 

In [119]:
df = pd.DataFrame(X)

In [120]:
df['LR'] = df['LR'].astype(str).apply(literal_eval)
df['RL'] = df['RL'].astype(str).apply(literal_eval)
df['TB'] = df['TB'].astype(str).apply(literal_eval)
df['BT'] = df['BT'].astype(str).apply(literal_eval)
df['Density'] = df['Density'].astype(str).apply(literal_eval) 

In [121]:
dis = []
length = len(df)
#print(length)
for i in range(0,length):
    #print(i)
    arr = np.array(df['LR'][i]+df['RL'][i]+df['TB'] [i]+df['BT'][i] )
    arr= np.append(arr,df['Density'][i])
    arr= np.append(arr,df['Ratio0'][i])
    arr= np.append(arr,df['Ratio1'][i])
    arr= np.append(arr,df['Ratio2'][i])
    arr= np.append(arr,df['Ratio3'][i])
    arr= np.append(arr,df['Ratio4'][i])
    arr= np.append(arr,df['Ratio5'][i])
    arr= np.append(arr,df['Ratio6'][i])
    arr= np.append(arr,df['Ratio7'][i])
    dis.append(arr)
    
#dis

In [122]:
X_train, X_test, y_train, y_test = train_test_split(dis, y, test_size = 0.20)
#X_train

In [123]:
#y_test

In [124]:
mm_scaler = preprocessing.MinMaxScaler()
X_train_minmax = mm_scaler.fit_transform(X_train)
mm_scaler.transform(X_test)

array([[1.        , 1.        , 1.        , ..., 0.6666    , 0.        ,
        0.        ],
       [1.        , 1.        , 1.        , ..., 0.4       , 0.20012001,
        0.32      ],
       [1.        , 1.        , 0.39583333, ..., 0.2624    , 0.26612661,
        0.4042    ],
       ...,
       [1.        , 1.        , 1.        , ..., 0.2524    , 0.19861986,
        0.4606    ],
       [1.        , 1.        , 0.75      , ..., 0.2704    , 0.29522952,
        0.3524    ],
       [1.        , 1.        , 0.27083333, ..., 0.2706    , 0.33333333,
        0.3768    ]])

In [125]:
#X_train

In [126]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear', C=1.0, probability=False, degree=3, coef0=0.0, 
cache_size=100.0, gamma=0.00666666666667)
model = svclassifier.fit(X_train, y_train)

In [127]:
y_pred = svclassifier.predict(X_test)

In [128]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[10  3  0 ...  0  0  0]
 [ 4  6  0 ...  0  0  0]
 [ 0  0 29 ...  0  0  0]
 ...
 [ 0  0  0 ... 31  0  0]
 [ 0  0  0 ...  0  3  0]
 [ 0  1  0 ...  0  0 48]]
              precision    recall  f1-score   support

           .       0.53      0.77      0.62        13
           ං       0.60      0.60      0.60        10
           අ       0.97      1.00      0.98        29
           ඉ       1.00      0.82      0.90        11
           උ       1.00      0.86      0.92         7
           එ       1.00      1.00      1.00         3
           ඔ       0.64      0.78      0.70        18
           ක       0.74      0.76      0.75        34
          කි       0.85      0.85      0.85        13
          කු       1.00      0.96      0.98        27
           ග       0.93      0.86      0.89        29
           ඝ       0.60      0.75      0.67         4
           ජ       0.94      1.00      0.97        17
           ට       0.60      0.64      0.62        28
          ටි       0.75      0.50

In [129]:
# get the accuracy
accuracy_score(y_test, y_pred)*100

83.49802371541502

In [131]:
filename = 'C:/CHARACTOR_RECOGNITION/NEW_DATA_FINAL_ALL_5.sav'
pickle.dump(model, open(filename, 'wb'))

In [132]:
loaded_model = pickle.load(open(filename, 'rb'))

In [133]:
y_pred

array(['ැ', 'යි', 'ව', ..., 'ඩ', 'ය', 'ත'], dtype=object)

In [134]:
y_pred[0]

'ැ'